name: Task Reminder

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  send-reminder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Run Reminder Script
        run: node scripts/reminder.js
        env:
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
